name: basketvibe
description: "LineUp - Basketball Community App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^9.2.1
  injectable: ^3.0.0

  # Functional Programming
  dartz: ^0.10.1

  # Navigation
  go_router: ^17.2.2

  # Maps & Location
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # Local Storage
  shared_preferences: ^2.3.2
  hive_flutter: ^1.1.0

  # Media
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Auth
  google_sign_in: ^6.2.1
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  internet_connection_checker: ^3.0.1

  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^3.2.5
  json_serializable: ^6.8.0
  injectable_generator: ^3.0.2

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"
