import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:basketvibe/core/styles/app_colors.dart';
import 'package:basketvibe/core/styles/app_spacing.dart';
import 'package:basketvibe/core/styles/app_text_styles.dart';
import 'package:basketvibe/core/styles/app_border_radius.dart';
import 'package:basketvibe/features/auth/presentation/cubit/auth_cubit.dart';
import 'package:basketvibe/features/auth/presentation/cubit/auth_state.dart';
import 'package:basketvibe/features/games/domain/entities/game_entity.dart';
import 'package:basketvibe/features/games/presentation/cubit/game_cubit.dart';
import 'package:basketvibe/features/games/presentation/cubit/game_state.dart';

/// Create a new game lobby ("The Run").
class CreateGamePage extends StatefulWidget {
  const CreateGamePage({super.key});

  @override
  State<CreateGamePage> createState() => _CreateGamePageState();
}

class _CreateGamePageState extends State<CreateGamePage> {
  final _formKey = GlobalKey<FormState>();
  final _courtNameController = TextEditingController();
  final _addressController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _maxPlayersController = TextEditingController(text: '10');

  DateTime? _selectedDate;
  TimeOfDay? _selectedTime;
  GameLevel _selectedLevel = GameLevel.balanced;
  GameVisibility _selectedVisibility = GameVisibility.public;
  int _maxPlayers = 10;

  @override
  void dispose() {
    _courtNameController.dispose();
    _addressController.dispose();
    _descriptionController.dispose();
    _maxPlayersController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(BuildContext context) async {
    final now = DateTime.now();
    final picked = await showDatePicker(
      context: context,
      initialDate: now,
      firstDate: now,
      lastDate: now.add(const Duration(days: 30)),
    );
    if (picked != null) {
      setState(() => _selectedDate = picked);
    }
  }

  Future<void> _selectTime(BuildContext context) async {
    final picked = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );
    if (picked != null) {
      setState(() => _selectedTime = picked);
    }
  }

  void _submitForm(BuildContext context) {
    if (!_formKey.currentState!.validate()) return;

    if (_selectedDate == null || _selectedTime == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Пожалуйста, выберите дату и время')),
      );
      return;
    }

    final hostId = context.read<AuthCubit>().state is AuthAuthenticated
        ? 'user_1' // TODO: Get actual user ID
        : 'guest_1';
    final hostName = 'Вы'; // TODO: Get actual user name

    // Combine date and time
    final startTime = DateTime(
      _selectedDate!.year,
      _selectedDate!.month,
      _selectedDate!.day,
      _selectedTime!.hour,
      _selectedTime!.minute,
    );

    final game = GameEntity(
      id: '', // Will be generated by repository
      courtId: 'court_${_courtNameController.text}',
      courtName: _courtNameController.text,
      city: 'Бишкек', // TODO: Get from location selector
      address: _addressController.text.isNotEmpty
          ? _addressController.text
          : _courtNameController.text,
      hostId: hostId,
      hostName: hostName,
      startTime: startTime,
      duration: const Duration(hours: 2), // Default 2 hours
      maxPlayers: _maxPlayers,
      currentPlayers: 1, // Host is included
      visibility: _selectedVisibility,
      level: _selectedLevel,
      status: GameStatus.open,
      description: _descriptionController.text.isNotEmpty
          ? _descriptionController.text
          : null,
    );

    context.read<GameCubit>().createGame(game);
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return BlocListener<GameCubit, GameState>(
      listener: (context, state) {
        if (state is GameCreated) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: const Text('Ран создан успешно!'),
              backgroundColor: AppColors.success,
            ),
          );
          context.pop();
        } else if (state is GameError) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(state.message),
              backgroundColor: AppColors.error,
            ),
          );
        }
      },
      child: Scaffold(
        backgroundColor: isDark ? AppColors.darkBg : AppColors.lightBg,
        appBar: AppBar(
          title: const Text('Создать ран'),
          leading: IconButton(
            icon: const Icon(Icons.close),
            onPressed: () => context.pop(),
          ),
        ),
        body: BlocBuilder<GameCubit, GameState>(
          builder: (context, state) {
            final isLoading = state is GameLoading;

            return Form(
              key: _formKey,
              child: SingleChildScrollView(
                padding: AppSpacing.pagePadding,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    AppSpacing.gapLG,
                    // Court Name
                    TextFormField(
                      controller: _courtNameController,
                      decoration: InputDecoration(
                        labelText: 'Площадка *',
                        hintText: 'Например: Восток-5',
                        border: OutlineInputBorder(
                          borderRadius: AppRadius.brMD,
                        ),
                      ),
                      style: AppTextStyles.bodyMD,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Введите название площадки';
                        }
                        return null;
                      },
                    ),
                    AppSpacing.gapMD,
                    // Address (optional)
                    TextFormField(
                      controller: _addressController,
                      decoration: InputDecoration(
                        labelText: 'Адрес (необязательно)',
                        hintText: 'Например: ул. Восток-5',
                        border: OutlineInputBorder(
                          borderRadius: AppRadius.brMD,
                        ),
                      ),
                      style: AppTextStyles.bodyMD,
                    ),
                    AppSpacing.gapMD,
                    // Date & Time
                    Row(
                      children: [
                        Expanded(
                          child: InkWell(
                            onTap: () => _selectDate(context),
                            child: Container(
                              padding: AppSpacing.cardPadding,
                              decoration: BoxDecoration(
                                border: Border.all(
                                  color: isDark
                                      ? AppColors.darkBorder
                                      : AppColors.lightBorder,
                                ),
                                borderRadius: AppRadius.brMD,
                              ),
                              child: Row(
                                children: [
                                  Icon(
                                    Icons.calendar_today,
                                    size: 20,
                                    color: AppColors.primary,
                                  ),
                                  AppSpacing.rowGapMD,
                                  Expanded(
                                    child: Text(
                                      _selectedDate == null
                                          ? 'Дата *'
                                          : DateFormat('dd.MM.yyyy')
                                              .format(_selectedDate!),
                                      style: AppTextStyles.bodyMD.copyWith(
                                        color: _selectedDate == null
                                            ? (isDark
                                                ? AppColors.darkTextSecondary
                                                : AppColors.lightTextSecondary)
                                            : (isDark
                                                ? AppColors.darkTextPrimary
                                                : AppColors.lightTextPrimary),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                        AppSpacing.rowGapMD,
                        Expanded(
                          child: InkWell(
                            onTap: () => _selectTime(context),
                            child: Container(
                              padding: AppSpacing.cardPadding,
                              decoration: BoxDecoration(
                                border: Border.all(
                                  color: isDark
                                      ? AppColors.darkBorder
                                      : AppColors.lightBorder,
                                ),
                                borderRadius: AppRadius.brMD,
                              ),
                              child: Row(
                                children: [
                                  Icon(
                                    Icons.access_time,
                                    size: 20,
                                    color: AppColors.primary,
                                  ),
                                  AppSpacing.rowGapMD,
                                  Expanded(
                                    child: Text(
                                      _selectedTime == null
                                          ? 'Время *'
                                          : _selectedTime!.format(context),
                                      style: AppTextStyles.bodyMD.copyWith(
                                        color: _selectedTime == null
                                            ? (isDark
                                                ? AppColors.darkTextSecondary
                                                : AppColors.lightTextSecondary)
                                            : (isDark
                                                ? AppColors.darkTextPrimary
                                                : AppColors.lightTextPrimary),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                    AppSpacing.gapMD,
                    // Max Players
                    TextFormField(
                      controller: _maxPlayersController,
                      decoration: InputDecoration(
                        labelText: 'Максимум игроков *',
                        hintText: '10',
                        border: OutlineInputBorder(
                          borderRadius: AppRadius.brMD,
                        ),
                      ),
                      keyboardType: TextInputType.number,
                      style: AppTextStyles.bodyMD,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Введите количество игроков';
                        }
                        final players = int.tryParse(value);
                        if (players == null || players < 2 || players > 20) {
                          return 'От 2 до 20 игроков';
                        }
                        _maxPlayers = players;
                        return null;
                      },
                    ),
                    AppSpacing.gapMD,
                    // Skill Level
                    Text(
                      'Уровень игры *',
                      style: AppTextStyles.labelMD.copyWith(
                        color: isDark
                            ? AppColors.darkTextPrimary
                            : AppColors.lightTextPrimary,
                      ),
                    ),
                    AppSpacing.gapSM,
                    SegmentedButton<GameLevel>(
                      segments: const [
                        ButtonSegment(
                          value: GameLevel.casual,
                          label: Text('Казуал'),
                        ),
                        ButtonSegment(
                          value: GameLevel.balanced,
                          label: Text('Средний'),
                        ),
                        ButtonSegment(
                          value: GameLevel.competitive,
                          label: Text('Профи'),
                        ),
                      ],
                      selected: {_selectedLevel},
                      onSelectionChanged: (Set<GameLevel> selection) {
                        setState(() => _selectedLevel = selection.first);
                      },
                    ),
                    AppSpacing.gapMD,
                    // Visibility
                    Text(
                      'Видимость',
                      style: AppTextStyles.labelMD.copyWith(
                        color: isDark
                            ? AppColors.darkTextPrimary
                            : AppColors.lightTextPrimary,
                      ),
                    ),
                    AppSpacing.gapSM,
                    SegmentedButton<GameVisibility>(
                      segments: const [
                        ButtonSegment(
                          value: GameVisibility.public,
                          label: Text('Публично'),
                        ),
                        ButtonSegment(
                          value: GameVisibility.friendsOnly,
                          label: Text('Друзья'),
                        ),
                        ButtonSegment(
                          value: GameVisibility.private,
                          label: Text('Приватно'),
                        ),
                      ],
                      selected: {_selectedVisibility},
                      onSelectionChanged: (Set<GameVisibility> selection) {
                        setState(() => _selectedVisibility = selection.first);
                      },
                    ),
                    AppSpacing.gapMD,
                    // Description
                    TextFormField(
                      controller: _descriptionController,
                      decoration: InputDecoration(
                        labelText: 'Описание (необязательно)',
                        hintText: 'Например: 3x3, intermediate, bring dark tee',
                        border: OutlineInputBorder(
                          borderRadius: AppRadius.brMD,
                        ),
                      ),
                      style: AppTextStyles.bodyMD,
                      maxLines: 3,
                    ),
                    AppSpacing.gapXL,
                    // Submit Button
                    ElevatedButton(
                      onPressed: isLoading ? null : () => _submitForm(context),
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        backgroundColor: AppColors.primary,
                        foregroundColor: Colors.white,
                        shape: RoundedRectangleBorder(
                          borderRadius: AppRadius.brMD,
                        ),
                      ),
                      child: isLoading
                          ? const SizedBox(
                              height: 20,
                              width: 20,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                valueColor:
                                    AlwaysStoppedAnimation<Color>(Colors.white),
                              ),
                            )
                          : Text(
                              'Создать ран',
                              style: AppTextStyles.buttonLG.copyWith(
                                color: Colors.white,
                              ),
                            ),
                    ),
                    AppSpacing.gapXL,
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
