// GENERATED CODE - DO NOT MODIFY BY HAND
// This file will be generated by build_runner
// Run: flutter pub run build_runner build

// For now, this is a placeholder. After running build_runner,
// this file will be auto-generated with all dependency registrations.
