// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3iIrV7fe4aAvyLKETCyB7fwRrhmc_dTY',
    appId: '1:309064225610:android:97a5822cff9cc5c679e7b3',
    messagingSenderId: '309064225610',
    projectId: 'line-up-cefa8',
    databaseURL: 'https://line-up-cefa8-default-rtdb.firebaseio.com',
    storageBucket: 'line-up-cefa8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqGRPQDrWmIVwIXKieEHV5MmPKNcmpQaY',
    appId: '1:309064225610:ios:e2cd5bca814eda0c79e7b3',
    messagingSenderId: '309064225610',
    projectId: 'line-up-cefa8',
    databaseURL: 'https://line-up-cefa8-default-rtdb.firebaseio.com',
    storageBucket: 'line-up-cefa8.firebasestorage.app',
    androidClientId: '309064225610-knffttue2iu8v4qurorq0qfsebtmhatp.apps.googleusercontent.com',
    iosClientId: '309064225610-g7j7ue350eau1ikmlmi81kijgrooobio.apps.googleusercontent.com',
    iosBundleId: 'com.example.basketvibe',
  );
}
